# Generated by Django 4.2 on 2023-04-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=300)),
                ('event_date', models.DateTimeField()),
                ('event_status', models.CharField(choices=[('Completed', 'Completed'), ('Incoming', 'Incoming')], max_length=100)),
            ],
        ),
    ]
