# Generated by Django 4.2 on 2023-04-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=300)),
                ('event_date', models.DateTimeField()),
                ('event_status', models.CharField(choices=[('Completed', 'Completed'), ('Upcoming', 'Upcoming')], max_length=100)),
                ('event_flyer', models.ImageField(upload_to='flyers')),
            ],
        ),
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=200)),
                ('recording', models.FileField(upload_to='recordings')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
