# Generated by Django 4.2 on 2023-04-15 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventday_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventday',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ref', to='events.event'),
        ),
    ]
