# Generated by Django 4.2 on 2023-04-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventday_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventday',
            name='day_flyer',
            field=models.ImageField(blank=True, null=True, upload_to='dayflyer'),
        ),
    ]
