# Generated by Django 4.2 on 2023-07-02 17:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_flyer',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='eventday',
            name='day_flyer',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
