# Generated by Django 4.2 on 2023-07-02 18:44

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, choices=[('VIP', 'VIP'), ('EXECUTIVE', 'EXECUTIVE'), ('AMBASSADOR', 'AMBASSADOR')], max_length=300, null=True)),
                ('donation_amount', models.IntegerField(blank=True)),
                ('registered_at', models.DateField(auto_now_add=True)),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_ref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_ref', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pay_date',),
            },
        ),
    ]
