# Generated by Django 4.2 on 2023-04-21 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='account_type',
            field=models.CharField(blank=True, choices=[('VIP', 'VIP'), ('EXECUTIVE', 'EXECUTIVE'), ('AMBASSADOR', 'AMBASSADOR')], max_length=300),
        ),
        migrations.AlterField(
            model_name='partner',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
