# Generated by Django 4.2 on 2023-04-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_alter_partner_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='account_type',
            field=models.CharField(blank=True, choices=[('VIP', 'VIP'), ('EXECUTIVE', 'EXECUTIVE'), ('AMBASSADOR', 'AMBASSADOR')], max_length=300, null=True),
        ),
    ]
