# Generated by Django 4.2 on 2023-04-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_transactions_partner_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile-pictures'),
        ),
    ]
