# Generated by Django 4.2 on 2023-04-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_donation_delete_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pay_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
