# Generated by Django 4.2 on 2023-04-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_alter_donation_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
