# Generated by Django 4.2 on 2023-04-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_donation_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='verfied',
            new_name='verified',
        ),
    ]
