# Generated by Django 4.2 on 2023-07-02 17:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_rename_verfied_donation_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ('-pay_date',)},
        ),
        migrations.AlterField(
            model_name='partner',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
