# Generated by Django 4.2 on 2023-04-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=500)),
                ('item_type', models.CharField(choices=[('merch', 'merch'), ('book', 'book')], max_length=300)),
                ('item_price', models.IntegerField(default=0)),
                ('item_link', models.URLField(blank=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
