# Generated by Django 4.2 on 2023-04-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopitem_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='item_desc',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='item_type',
            field=models.CharField(choices=[('merch', 'merch'), ('book', 'book'), ('limited', 'limited'), ('work-book', 'work-book')], max_length=300),
        ),
    ]
